config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'gossips#index'
  resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
       if @gossip.save
        redirect_to @gossip
      else
        render :new
      end
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render 'edit'
    end

  end

  def index
    @gossips = Gossip.all
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end


  private

  def gossip_params
      params.require(:gossip).permit(:anonymous_author, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Bienvenue sur la page où tu peux éditer ton gossip</h1>

<%= form_for(@gossip) do |f| %>
  
  <p>
  <%= f.label :anonymous_author, value:"Votre pseudo d'auteur anonyme" %>
  <br />
  <%= f.text_field :anonymous_author, placeholder: @gossip.anonymous_author %>
  </p>

  <p>
  <%= f.label :content, value:"Votre gossip ici" %>
  <br />
  <%= f.text_field :content, placeholder: @gossip.content, size: 150%>
  </p>

  <p>
    <%= f.submit "Modifie ton gossip !!!" %>
  </p>


<% end %>

app/views/gossips/index.html.erb
<h1>Bienvenue sur the Hacking Gossip !</h1>

<p>Voici la liste des différents gossips...</p>


<table>
<tr>
  <th>Auteur</th>
  <th>Gossip</th>
  <th></th>
</tr>
<% @gossips.each do |gossip| %>
<tr>
  <td><%= gossip.anonymous_author %></td>
  <td><%= gossip.content %></td>
  <td><%= link_to "Voir", "gossips/#{gossip.id}" %></td>

</tr>
<% end %>
</table>

<p>Tu veux toi aussi créer ton gossip ? <button><%= link_to "Gossiiiiip !!", 'gossips/new' %></button> </p>

app/views/gossips/new.html.erb
<h1>Formulaire de création d'un gossip</h1>

<%= form_for(@gossip) do |f| %>
  
  <p>
  <%= f.label :anonymous_author, value:"Votre pseudo d'auteur anonyme" %>
  <br />
  <%= f.text_field :anonymous_author %>
  </p>

  <p>
  <%= f.label :content, value:"Votre gossip ici" %>
  <br />
  <%= f.text_field :content, placeholder:'Par exemple raconte qui tu as vu sortir du hangar à 8h du matin car il avait passé la nuit là...', size: 150%>
  </p>

  <p>
    <%= f.submit "Balance le gossip !!!" %>
  </p>


<% end %>

app/views/gossips/show.html.erb
<h1>Voici le Gossip...</h1>

<p><%= @gossip.content %></p>

<p></p>

<p><%= @gossip.anonymous_author%></p>

<%= link_to 'Clique pour détruire', @gossip, method: :delete %>
<p><%= link_to "Modifier le gossip", edit_gossip_path %></p>
<p><%= link_to "Retour à la liste des gossips", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-0.8.1.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>